### ISSUE TITLE
TODO list (not that emergent)

### ISSUE THREAD

**Issue by xjtuwxg** [ssrg-vt/DynaCut#11]
- [x]  The tool does not work well on Ubuntu 18.04
- [x]  We need to find a name for this project (PopSnapshot will be used by another student soon)
- [ ]  Apply googletest (https://github.com/google/googletest) to this project.
- [ ] madvise system call -> pages maybe swapped to disk, how to handle ?
- [ ] Generate trap list using a tool. No manual intervention
