### ISSUE TITLE
TODO list (for recycling the paper)

### ISSUE THREAD

**Issue by xjtuwxg** [ssrg-vt/DynaCut#20]
- [ ] Fig 1: add color for init code (R2)
- [ ] Add a comparison table for DynaCut v.s. related works (R1)
- [ ] Add a graph of code coverage (y-axis) changes through the time (x-axis), and can compare against existing works. (R1)
- [ ] Improve the init BB identification
- [ ] Correctness of the code removal.
- [ ] Different config file v.s. debloating
